/* FILTRANDO DADOS COM WHERE E LIKE */
/* WHERE = ONDE
LIKE = COMO 

PROJEÇÃO = SELECT
SELEÇÃO = WHERE
*/


SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ'; /*EMPTY SET = VAZIO */
