
CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE LIVROS (
	NOME_LIVRO VARCHAR(100),
	NOME_AUTOR VARCHAR(100),
	SEXO_AUTOR CHAR(1),	
	NUMERO_PAGINAS INT(5),
	NOME_EDITORA VARCHAR(30),
	VALOR_LIVRO FLOAT(10,2),
	UF_EDITORA CHAR(2),
	ANO_PUBLICACAO INT(4)
);

SHOW DATABASE;

USE LIVRARIA;

/* STATUS MOSTRA EM QUAL DATABASE ESTÁ*/

INSERT INTO LIVROS VALUES('CAVALEIRO REAL ' , 'ANA CLAUDIA', 'F', 465 , 'ATLAS' , 49.9 , 'RJ' , 2009 );

INSERT INTO LIVROS VALUES('SQL PARA LEIGOS ' , 'JOÃO NUNES', 'M', 450 , 'ADDISON' , 98 , 'SP' , 2018 );

INSERT INTO LIVROS VALUES('Receitas Caseiras ' , 'Celia Tavares', 'F', 210 , 'ATLAS' , 45 , 'RJ' , 2008 );

INSERT INTO LIVROS VALUES('Pessoas Efetivas ' , 'Eduardo Santos', 'M', 390 , 'BETA' , 78.99 , 'RJ' , 2018 );

INSERT INTO LIVROS VALUES('Habitos Saudáveis ' , 'Eduardo Santos', 'M', 630 , 'BETA' , 150.98 , 'RJ' , 2019 );

INSERT INTO LIVROS VALUES('A Casa Marrom ' , 'Hermes Macedo', 'M', 250 , 'BUBBA' , 60 , 'MG' , 2016 );

INSERT INTO LIVROS VALUES('Estacio Querido' , 'Geraldo Francisco', 'M', 310 , 'INSIGNIA' , 100 , 'ES' , 2015 );

INSERT INTO LIVROS VALUES('Pra sempre amigas' , 'Leda Silva', 'F', 510 , 'INSIGNIA' , 78.98 , 'ES' , 2011 );

INSERT INTO LIVROS VALUES('Copas Inesqueciveis' , 'Marco Alcantara', 'M', 200 , 'LARSON' , 130.98 , 'RS' , 2018 );

INSERT INTO LIVROS VALUES('O poder da mente' , 'Clara Mafra', 'F', 120 , 'CONTINENTAL' , 56.58 , 'SP' , 2017 );

/* TRAZER TODOS OS LIVROS */

SELECT * FROM LIVROS;

/* TRAZER O NOME DO LIVRO E O NOME DA EDITORA */ /* TRABALHANDO COM SELEÇÃO = WHERE */

SELECT NOME_LIVRO, NOME_EDITORA
FROM LIVROS;

/* TRAZER O NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS POR AUTORES MASCULINOS */
/* TRAZER O NOME DO LIVRO E A UF DOS LIVROS = PROJEÇÃO */
/* PUBLICADOS POR AUTORES MASCULINOS = SELEÇÃO */

SELECT NOME_LIVRO, UF_EDITORA
FROM LIVROS
WHERE SEXO_AUTOR = 'M';

/* CONFERINDO */

SELECT NOME_AUTOR, NOME_LIVRO, UF_EDITORA
FROM LIVROS
WHERE SEXO_AUTOR = 'M';

/* TRAZER O NOME DO LIVRO E O NÚMERO DE PÁGINAS DOS LIVROS PUBLICADOS POR AUTORES FEMININOS */
/* TRAZER O NOME DO LIVRO E O NÚMERO DE PÁGINAS DOS LIVROS  = PROJEÇÃO */
/* PUBLICADOS POR AUTORES FEMININOS = SELEÇÃO */

SELECT NOME_LIVRO, NUMERO_PAGINAS
FROM LIVROS
WHERE SEXO_AUTOR = 'F';

/* CONFERINDO */

SELECT NOME_AUTOR, NOME_LIVRO, NUMERO_PAGINAS
FROM LIVROS
WHERE SEXO_AUTOR = 'F';

/* TRAZER NOME E OS VALORES DOS LIVROS DAS EDITORAS DE SP */

SELECT NOME_LIVRO, VALOR_LIVRO
FROM LIVROS
WHERE UF_EDITORA = 'SP';

/* CONFERINDO */

SELECT UF_EDITORA, NOME_LIVRO, VALOR_LIVRO
FROM LIVROS
WHERE UF_EDITORA = 'SP';


/* TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS EM SP OU RJ */

SELECT NOME_AUTOR, SEXO_AUTOR
FROM LIVROS
WHERE SEXO_AUTOR = 'M'
AND UF_EDITORA = 'SP'
OR UF_EDITORA = 'RJ';

