
/* GROUP BY */

SELECT COUNT (*) 
FROM CLIENTE
GROUP BY SEXO;

/* USAR A FUNÇÃO DE AGREGAÇÃO COM AGRUPAMENTO PARA TRAZER OS DADOS DISTRIBUINDO POR QUANTIDADE */

SELECT COUNT (*) 
FROM CLIENTE
GROUP BY SEXO;