/* PARA GANHAR PERFORMACE COM OPERADORES LÓGICOS */

/* SUPONHA 1 Milhão de registros

OR = SEMPRE COLOCAR COMO PRIMEIRA OPÇÃO A CONDIÇÃO QUE TEM MAIS CHANCHE DE SER VERDADEIRA, SENDO ASSIM A SEGUNDA NÃO SERÁ CHECADA (OU = PARA SER VERDADE PELO MENOS UMA CONDIÇÃO COMO VERDADEIRA)

AND = PARA ESSA CHECAGEM AS 2 TEM QUE SER VERDADEIRAS, SENDO ASSIM COLOCAR A PRIMEIRA CONDIÇÃO COM MENOS PORCENTAGEM DE DADOS POR EXEMPLO, FAZENDO O BANCO PASSAR PELA SEGUNDA CONDIÇÃO MENOS VEZES ( E = PARA SER VERDADE AS DUAS CONDIÇÕES TEM QUE SER VERDADEIRAS)

*/