
/* Usando DELETE para excluir dados de uma tabela*/

/* Sempre usar o DELETE com o WHERE */

/* Sempre confire e conte os dados */

SELECT COUNT(*) FROM CLIENTE; --vai mostrar o total de registros

SELECT COUNT(*) FROM CLIENTE -- Vai contar comente pela seleção por nome por exemplo
WHERE NOME = 'MARIA';

DELETE FROM CLIENTE
WHERE NOME = 'MARIA';

SELECT COUNT(*) FROM CLIENTE;

INSERT INTO CLIENTE(NOME, EMAIL, TELEFONE, ENDERECO, SEXO, CPF) VALUES("CARLA" , "C.LOPES@GMAIL.COM" , "4575-0048" , "RUA COPER LEAF - WILLIANSBURG - KITCHENER", "F", 456388549);

INSERT INTO CLIENTE(NOME, EMAIL, TELEFONE, ENDERECO, SEXO, CPF) VALUES("CARLA" , "C.@GMAIL.COM" , "4575-0048" , "RUA COPER LEAF - WILLIANSBURG - KITCHENER", "F", 456388549);

INSERT INTO CLIENTE(NOME, EMAIL, TELEFONE, ENDERECO, SEXO, CPF) VALUES("MARCOS" , "MARCOS@GMAIL.COM" , "4575-0048" , "RUA COPER LEAF - WILLIANSBURG - KITCHENER", "F", 456388549);


SELECT * FROM CLIENTE;

SELECT * FROM CLIENTE 
WHERE NOME = 'CARLA'
OR EMAIL = 'C.@GMAIL.COM'; -- OR TRAZ TODO MUNDO COM PELO MENOS UMA SAS DUAS CONDIÇOES

DELETE FROM CLIENTE 
WHERE NOME = 'CARLA'
OR EMAIL = 'C.@GMAIL.COM';

SELECT * FROM CLIENTE;

SELECT * FROM CLIENTE 
WHERE NOME = 'CARLA'
AND EMAIL = 'C.@GMAIL.COM'; -- AND TRAZ APENAS O REGISTRO QUE SATISFAÇA AS DUAS CONDIÇÕES
 
DELETE FROM CLIENTE 
WHERE NOME = 'CARLA'
AND EMAIL = 'C.@GMAIL.COM';