
CREATE DATABASE COMERCIO;

USE COMERCIO;

SHOW DATABASES;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT, -- id sempre será um identificador e auto incremente, sempre será adicionado automaticamente pelo banco
	NOME VARCHAR (30) NOT NULL, -- NOT NULL é o campo que não poderá ser nulo
	SEXO ENUM ('M', 'F') NOT NULL, -- enum é um enumerado de tipos
	EMAIL VARCHAR (50) UNIQUE,  -- Unique sempre será o dado que não se repetirá
	CFP VARCHAR (15) UNIQUE
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE, -- PARA SE REFERENCIAR UMA CHAVE ESTRANGEIRA DEVE SE USAR O MESMO TIPO DO ID DA TABELA PRINCIPAL
	FOREIGN KEY (ID_CLIENTE) -- ADICIONAR A CLAUSULA UNIQUE EM TABELAS COM CARDINALIDAD E (1,1)
	REFERENCES CLIENTE(IDCLIENTE) -- CHAVE ESTRANGEIRA ID_CLIENTE, REFERENCIA DA TABELA CLIENTE, DO CAMPO CHAVE PRIMARIA IDCLIENTE
);


CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,	
	TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT, -- PARA SE REFERENCIAR UMA CHAVE ESTRANGEIRA DEVE SE USAR O MESMO TIPO DO ID DA TABELA PRINCIPAL
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE) -- CHAVE ESTRANGEIRA ID_CLIENTE, REFERENCIADA DA TABELA CLIENTE, DO CAMPO CHAVE PRIMARIA IDCLIENTE
);

/* endereco - obrigatorio
cadastro de somente um,

telefone - não obrigatório
cadastro de mais de um (opcional) */

/*FOREIGN key depende da cardinalidade para ser direcionado a ser uma chave estrangeira em uma tabela

Regra de negócio*/

/*
Em relacionamento (1,1) a chave estrangeira fica na tabela mais fraca, a que a é não principal,
Em relacionamento (1,N) a chave estrangeira ficará na tabela de cardinalidade N, */


USE COMERCIO ;
SHOW TABLES;

DESC CLIENTE;
INSERT INTO CLIENTE VALUES (NULL, 'JOAO', 'M', 'JOAO@GMAIL.COM', '76576576576');
INSERT INTO CLIENTE VALUES (NULL, 'CARLOS', 'M','CARLOS@GMAIL.COM', '67495137854');
INSERT INTO CLIENTE VALUES (NULL, 'ANA', 'F', 'ANA@GMAIL.COM', '96458231749');
INSERT INTO CLIENTE VALUES (NULL, 'CLARA','F', NULL, '98546732164');
INSERT INTO CLIENTE VALUES (NULL, 'CELIA', 'F', 'CELIA@GMAIL.COM', '65478932146');
INSERT INTO CLIENTE VALUES (NULL, 'MARIA', 'F', 'MARIA@GMAIL.COM', '12345678979');


SELECT * FROM CLIENTE; 

DESC ENDERECO;
/*QUANDO SE TEM UM UNIQUE NA CHAVE ESTRANGUEIRA DE UMA TABELA COM CARDINALIDADE (1,1), SIGNIFICA QUE SERÁ INSERIDO UM UNICO DADO DE RELACIONAMENTO NA TABELA QUE REFERENCIA A CHAVE PRIMARIA */
INSERT INTO ENDERECO VALUES (NULL, 'RUA ANTONIO SA', 'CENTRO', 'B. HORIZONTE','MG', 4);
INSERT INTO ENDERECO VALUES (NULL, 'RUA CAPITAO HERMES', 'CENTRO', 'RIO DE JANEIRO', 'RJ', 1);
INSERT INTO ENDERECO VALUES (NULL, 'RUA PRES. VARGAS', 'JARDINS', 'SAO PAULO', 'SP', 3);
INSERT INTO ENDERECO VALUES (NULL, 'RUA ALFANDEGA', 'ESTACIO', 'RIO DE JANEIRO', 'RJ', 2);
INSERT INTO ENDERECO VALUES (NULL, 'RUA DO OUVIDOR', 'FLAMENGO', 'RIO DE JANEIRO', 'RJ', 6);
INSERT INTO ENDERECO VALUES (NULL, 'RUA URUGUAINA', 'CENTRO', 'VITORIA', 'ES', 5);

SELECT * FROM ENDERECO; 

DESC TELEFONE;
/*QUANDO NÃO SE TEM UM UNIQUE NA CHAVE ESTRANGUEIRA DE UMA TABELA COM CARDINALIDADE (1,N), SIGNIFICA QUE PODERÁ SER INSERIDO VÁRIOS DADOS DE RELACIONAMENTO NA TABELA QUE REFERENCIA A CHAVE PRIMARIA*/
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '659847125', 5);
INSERT INTO TELEFONE VALUES (NULL, 'RES', '84776523', 5);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '554781238', 1);
INSERT INTO TELEFONE VALUES (NULL, 'COM', '95784623', 2);
INSERT INTO TELEFONE VALUES (NULL, 'RES', '33568897', 1);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '885746658', 3);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '558796643', 3);
INSERT INTO TELEFONE VALUES (NULL, 'COM', '86547451', 1);
INSERT INTO TELEFONE VALUES (NULL, 'RES', '78451236', 5);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '897456823', 2);

SELECT * FROM TELEFONE; 
