/* AVG - TRAZ O VALOR MÉDIO DE UMA COLUNA, CONTA AS COLUNAS, SOMA OS VALORES E DEPOIS DIVIDE */

SELECT AVG(VALOR) AS MEDIA_VALOR
FROM CURSOS;

+-------------+
| MEDIA_VALOR |
+-------------+
| 2820.000000 |
+-------------+