/* CURSORES */ 

CREATE DATABASE CURSORES;

USE CURSORES;

CREATE TABLE VENDEDORES(
		IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
		NOME VARCHAR(30),
		JANEIRO INT,
		FEVEREIRO INT,
		MARCO INT
);

INSERT INTO VENDEDORES VALUES (NULL, 'MARIA', 3548, 6678, 9964);
INSERT INTO VENDEDORES VALUES (NULL, 'CLARA', 5456, 6475, 2364);
INSERT INTO VENDEDORES VALUES (NULL, 'JOAO', 3558, 9654, 7842);
INSERT INTO VENDEDORES VALUES (NULL, 'ANTONIO', 7568, 4569, 2347);
INSERT INTO VENDEDORES VALUES (NULL, 'JOSE', 7845, 9856, 3365);
INSERT INTO VENDEDORES VALUES (NULL, 'LILIAN', 7755, 4496, 3377);

SELECT * FROM VENDEDORES;

+------------+---------+---------+-----------+-------+
| IDVENDEDOR | NOME    | JANEIRO | FEVEREIRO | MARCO |
+------------+---------+---------+-----------+-------+
|          1 | MARIA   |    3548 |      6678 |  9964 |
|          2 | CLARA   |    5456 |      6475 |  2364 |
|          3 | JOAO    |    3558 |      9654 |  7842 |
|          4 | ANTONIO |    7568 |      4569 |  2347 |
|          5 | JOSE    |    7845 |      9856 |  3365 |
|          6 | LILIAN  |    7755 |      4496 |  3377 |
+------------+---------+---------+-----------+-------+

CREATE TABLE VEND_TOTAL(
		NOME VARCHAR(30),
		JANEIRO INT,
		FEVEREIRO INT,
		MARCO INT,
		TOTAL INT,
		MEDIA INT

);



CREATE PROCEDURE INSEREDADOS()
BEGIN
	
	/*VARIAVEL CHAMADA FIM DO TIPO INTEIRO VALOR INICIAL É O 0*/
	DECLARE FIM INT DEFAULT 0;

	/*VARIAVEIS DO TIPO INTEIRO*/	
	DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA INT;

	/*VARIAVEL NOME DO TIPO VARCHAR*/
	DECLARE VNOME VARCHAR(50);

	/*VARIAVEL REG DO TIPO CURSOR, QUE VAI RECEBER 4 VALORES*/
	DECLARE REG CURSOR FOR(
		SELECT NOME, JANEIRO, FEVEREIRO, MARCO FROM VENDEDORES
		);

	/*ROBOZINHOQUE FICA OLHANDO A VETOR, E VER QUE NÃO TEM MAIS ELEMENTOS PARA SER CHAMADO, COLOCA A VARIAVEL QUE RECEBE DEFAULT QUE INICIOU COM ZERO, COLOCA =1 FAZENDO O LUP PARAR DE EXECUTAR*/
	/*HANDLER= VARIAVEL DE MANIPULAÇÃO CONTINUA*/
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1

	/* O QUE SERÁ DIFERENTE PARA O HANDLER, SERÁ O QUE FOR COLOCADO NAS VARIAVEIS E TBM NA QUERY*/

	OPEN REG;
	/*OPEN, VAI PEGAR A MINHA VARIAVEL REG E JOGAR PARA A MEMORIA RAM, DADOS EM MEMORIA*/

	/*LOOP*/
	REPEAT 

		FETCH REG INTO VNOME, VAR1, VAR2, VAR3;

		/* SE A VARIAVEL FIM, NÃO FOR VERDADEIRO, CONTINUE*/
		IF NOT FIM THEN

			SET VTOTAL = VAR1 + VAR2 + VAR3;
			SET VMEDIA = VTOTAL / 3;

			INSERT INTO VEND_TOTAL VALUES(VNOME, VAR1, VAR2, VAR3, VTOTAL, VMEDIA);
		END IF;	

	UNTIL FIM END REPEAT;

	CLOSE REG;

END

DELIMITER $


CREATE PROCEDURE INSEREDADOS()

BEGIN	

	DECLARE FIM INT DEFAULT 0;
	DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA INT;
	DECLARE VNOME VARCHAR(50);

	DECLARE REG CURSOR FOR(
		SELECT NOME, JANEIRO, FEVEREIRO, MARCO FROM VENDEDORES
		);

	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;

	OPEN REG;

	REPEAT 

		FETCH REG INTO VNOME, VAR1, VAR2, VAR3;

		IF NOT FIM THEN

			SET VTOTAL = VAR1 + VAR2 + VAR3;
			SET VMEDIA = VTOTAL / 3;

			INSERT INTO VEND_TOTAL VALUES(VNOME, VAR1, VAR2, VAR3, VTOTAL, VMEDIA);

		END IF;	

	UNTIL FIM END REPEAT;

	CLOSE REG;

END


$

DELIMITER ;

SELECT * FROM VENDEDORES;
SELECT * FROM VEND_TOTAL;

CALL INSEREDADOS();

CALL INSEREDADOS();
Query OK, 0 rows affected (0.58 sec)

mysql> SELECT * FROM VEND_TOTAL;
+---------+---------+-----------+-------+-------+-------+
| NOME    | JANEIRO | FEVEREIRO | MARCO | TOTAL | MEDIA |
+---------+---------+-----------+-------+-------+-------+
| MARIA   |    3548 |      6678 |  9964 | 20190 |  6730 |
| CLARA   |    5456 |      6475 |  2364 | 14295 |  4765 |
| JOAO    |    3558 |      9654 |  7842 | 21054 |  7018 |
| ANTONIO |    7568 |      4569 |  2347 | 14484 |  4828 |
| JOSE    |    7845 |      9856 |  3365 | 21066 |  7022 |
| LILIAN  |    7755 |      4496 |  3377 | 15628 |  5209 |
+---------+---------+-----------+-------+-------+-------+