/* Oficina do Sr. José*/

/*

Cadastrar carros que entrarm para realizar serviços e seus donos.
Cada cliente possui apenas um carro,
Um carro possui apenas uma marca,
As cores dos carros, 
Os carros podem ter mais de uma cor,
Armazenar os telefones dos  clientes, que não são obrigatórios.


*/

CREATE DATABASE OFICINA;

CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    CPF CHAR(11) NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    SEXO ENUM('F', 'M') NOT NULL,
    ID_CARRO INT UNIQUE 

);

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TPO ENUM('CEL', 'RES', 'COM') NOT NULL,
    NUMERO VARCHAR(30) NOT NULL,
    ID_CLIENTE INT 

);

CREATE TABLE MARCA(
    IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
    MARCA VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE CARRO(
    IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR(30) NOT NULL,
    ANO VARCHAR(10) NOT NULL,
    PLACA VARCHAR(10) NOT NULL UNIQUE,
    ID_MARCA INT 
);

CREATE TABLE COR(
    IDCOR INT PRIMARY KEY AUTO_INCREMENT,
    COR VARCHAR(30) UNIQUE NOT NULL

);

CREATE TABLE CARRO_COR(
    ID_COR INT ,
    ID_CARRO INT,
   PRIMARY KEY (ID_CARRO, ID_COR)
);

/*constraints , BOA PRÁTICA CRIAR AS TABELAS DEPOIS CRIAR AS CHAVES ESTRANGEIRAS*/

ALTER TABLE TELEFONE 
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CLIENTE 
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY (ID_CARRO)
REFERENCES CARRO(IDCARRO);

ALTER TABLE CARRO 
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY (ID_MARCA)
REFERENCES MARCA(IDMARCA);

ALTER TABLE CARRO_COR 
ADD CONSTRAINT FK_COR
FOREIGN KEY (ID_COR)
REFERENCES COR(IDCOR);

ALTER TABLE CARRO_COR 
ADD CONSTRAINT FK_CARRO
FOREIGN KEY (ID_CARRO)
REFERENCES CARRO(IDCARRO);


